### ISSUE TITLE
Dependency graph visualization

### ISSUE THREAD

**Issue by ktraunmueller** [wojteklu/depcheck#1]
It would be nice to have a visual representation of the dependency graph (an image). You could use dotty and graphviz (http://www.graphviz.org) for that.

**Comment by wojteklu** [comment]
@ktraunmueller I added command for generating visual representation of the dependency graph in 0.3. Thanks for the suggestion!

**Comment by aimak** [comment]
Hi everyone. 
Thanks a lot for depcheck and for resolving this issue, it's really useful.

I'm working on a really big project and this graph dependency is really messy. Do you think there would be any way to re-scope depcheck and/or graphviz in order to have more meaningful dependencies ?

Thank you !

**Comment by ghost** [comment]
@aimak Do you have some suggestions of ways to make the dependency graph more useful for you?

**Comment by aimak** [comment]
@aamctustwo I don't know what is possible but I'm thinking of restricting depcheck to a folder for instance.
Or something smarter like `depcheck graph UserProvider.swift` and only show the whole tree if the node has less than N dependencies. 
What do you think ?

**Comment by wojteklu** [comment]
@aimak Cool idea! It is possible to make graph only for specific class, so you will see its dependencies and dependants. Command would look like `depcheck graph UserProvider`. Eventually you can pass array of classes or maybe directory? What do you think?

**Comment by aimak** [comment]
@wojteklu All three suggestions sound really good to me. I would love to have the possibility to pass a class, an array of class or a directory !

**Comment by wojteklu** [comment]
@aimak @aamctustwo Implemented possibility to constraint graph's nodes. You can pass regexp using option `include` in graph command. It will constraint dependants and dependencies based on passed regexp.

`depcheck graph --project Example.xcodeproj --include "ViewController"`

![graph](https://cloud.githubusercontent.com/assets/2467222/19288682/7e3f4dde-9007-11e6-99a6-6047c5412e5e.png)

If you want include a list of files:

`depcheck graph --project Example.xcodeproj --include "\b(ViewController|Model1)\b"`

**Comment by ghost** [comment]
@wojteklu I like it!

**Comment by aimak** [comment]
This looks great. However, I'm not sure how to use it. Now I get something like

   [A]   [B]   [C]
     \      |      /
[ViewController]

when I `depcheck graph --project Example.xcodeproj --include "ViewController"` although I _know_ that `ViewController` has dependencies.

The thing that I suggested was more : display all `ViewController` subtrees except if a node's subtree has more than N nodes.
Does it make sense ?
