### ISSUE TITLE
Generating Graph for Watch.

### ISSUE THREAD

**Issue by p0kjin** [wojteklu/depcheck#12]
Currently depcheck does not support graphing for Watch with error message 
No derived data found. Please make sure the project was built.

I did some investigation and found out that this is because In the case of Watch, data are stored inside 'target_name Extension.build' (at least for my project). 

I was able to analyze and graph by manually adding ' Extension' inside Finder module.

**Comment by wojteklu** [comment]
Thanks! Could you attach sample project with the problem?

**Comment by wojteklu** [comment]
Fixed. Check out version 0.5.0. Thanks!
