### ISSUE TITLE
Ability to exclude pods or carthage dependency

### ISSUE THREAD

**Issue by funky-monkey** [wojteklu/depcheck#3]
First of all - cool tool! It gave me more insight into my project, so thanks for that!
Second, I would really like to see the ability to exclude certain folders like pods/carthage, because these tend to clutter the results.

Cheers, 
Sid

**Comment by vittoriom** [comment]
I know it's not a built-in solution, but in the mean time this is the depcheck command I run in my shell:

```
depcheck analyze --project MyProject.xcodeproj > depcheck.result && cat depcheck.result | sed '/Tests/d' | sed '/Mock/d' | sed '/SharedExample/d' | sed '/[0-1] $/d' | sed 's/^[0-9]\{1,5\}. //' | sort | uniq | sort -n -r -t - -k 2 | awk '{printf "%d. %s\n", NR, $0}' && rm depcheck.result
```

This is filtering out Tests, Mocks and SharedExampleGroups (a Quick/Nimble thing), removing classes with 0-1 dependencies and removing duplicates

**Comment by wojteklu** [comment]
@vittoriom @funky-monkey In newest version Pods/Carthage dependencies are excluded by default. Thanks for your help.
