### ISSUE TITLE
Dependencies doesn't take into account enum used inside other enum for it's associated value

### ISSUE THREAD

**Issue by asos-danieltavares** [wojteklu/depcheck#8]
```
enum ParentEnum {
    case Info(enumA: EnumA)
}

enum EnumA {
    case A
}
```

In this case EnumA is showing 0 dependency which is true, but would be nice if we could see if it's been used somewhere (like the case above)

**Comment by wojteklu** [comment]
I created sample project to recreate this issue. Results from running `analyze` command:

<img width="430" alt="screen shot 2016-08-31 at 20 11 58" src="https://cloud.githubusercontent.com/assets/2467222/18140773/3e2d67a0-6fb7-11e6-8f63-d1c05c6eafe1.png">

If you want to check if enum is used somewhere, run `usage` command:

<img width="341" alt="screen shot 2016-08-31 at 20 15 39" src="https://cloud.githubusercontent.com/assets/2467222/18141138/97c4d4be-6fb8-11e6-9996-157b46d87808.png">
